<style>
    #nette-debug .nette-elasticSearchPanel,
    #tracy-debug .nette-elasticSearchPanel { min-width: 700px; }
    #nette-debug .nette-elasticSearchPanel h2,
    #tracy-debug .nette-elasticSearchPanel h2 { font-size: 22px; font-weight: bold; }
    #nette-debug .nette-elasticSearchPanel small,
    #tracy-debug .nette-elasticSearchPanel small { font-size: 70%; font-weight: normal; }
    #nette-debug .nette-elasticSearchPanel code,
    #tracy-debug .nette-elasticSearchPanel code { font-size: 100%; font-weight: inherit; }
    #nette-debug .nette-elasticSearchPanel table,
    #tracy-debug .nette-elasticSearchPanel table { width: 100%; }
    #nette-debug .nette-elasticSearchPanel table th,
    #tracy-debug .nette-elasticSearchPanel table th { text-align: right; }
</style>

<?php foreach ($this->queries as $host => $queries): ?>
<h1 class="nette-elasticSearchPanel"><code><?php echo $esc($host) ?></code> - Queries: <?php echo $esc(count($queries)); ?>, time: <?php echo $esc($totalTime); ?> </h1>
<div class="nette-inner tracy-inner nette-elasticSearchPanel">
	<?php foreach($queries as $query): ?>
		<?php list($request, $response, $time) = $query; $info = $response ? $response->getTransferInfo() : array('url' => 'http://localhost:9200/'); $url = new \Nette\Http\Url($info['url']); ?>
		<h2>
			<code><?php echo $esc(strtoupper($request->getMethod())); ?> <?php echo $esc('/' . ltrim($url->path, '/')); ?></code>
			<small><?php echo $esc(number_format($time * 1000, 2)); ?>ms</small>
		</h2>

		<table>
			<?php if ($request->getData()) { ?><tr>
				<th width="70"><a href="json:<?php echo $esc(\Nette\Utils\Json::encode($extractRequestData($request))) ?>">Request:</th>
				<td><?php echo $click($extractRequestData($request), TRUE, 10); ?></td>
			</tr><?php } ?>
			<tr>
				<th width="70">Response:</th>
				<?php if ($response && $response->isOk()) { ?>
					<td><?php echo $click($response->getData(), TRUE, 10); ?></td>
				<?php } elseif (isset($query[3]) && $query[3] instanceof \Exception) { ?>
					<td style="color:red"><?php echo $esc($query[3]->getMessage()); ?></td>
				<?php } ?>
			</tr>
		</table>
	<?php endforeach; ?>
</div>
<?php endforeach; ?>
